const HistoricalReader=(()=>{
const base="governance/walkthroughs/",names=["PHASE_01_SOURCE_BOUND_ORIENTATION","PHASE_02_PRE_INCIDENT_OPERATIONAL_CONTEXT","PHASE_03_DEPLOYMENT_RECONSTRUCTION","PHASE_04_PRODUCTION_STATE_RECONSTRUCTION","PHASE_05_INCIDENT_EMERGENCE","PHASE_06_DETECTION_AND_VISIBILITY","PHASE_07_RESPONSE_AND_CONTAINMENT","PHASE_08_IMMEDIATE_OUTCOME","PHASE_09_LATER_OFFICIAL_FINDINGS","PHASE_10_EVIDENCE_GAP_REVIEW","PHASE_11_EXPERIENCE_AMPLIFICATION_REFLECTION_PREPARATION"],prefix="M9_KNIGHT_CAPITAL_PUBLISHED_HISTORICAL_WALKTHROUGH_01_";
const state={route:"orientation",phases:[],selectedPhase:null,selectedClaim:null,workingSet:[],visitedPhases:new Set(),reflection:{status:"unavailable",attributableIdentity:null},traceability:{claimId:null,sourceId:null,locator:null}};
const fields=["Claim text","Claim class","Walkthrough phase","Source identity","Citation locator","Attribution","Source date","Historical-knowledge status","Hindsight status","Confidence boundary","Contradictory source","Evidence-gap reference","Replay eligibility","Reviewer note"];
const clean=value=>value.replace(/`/g,"").replace(/\s+/g," ").trim();
function parseClaims(markdown){const headings=[...markdown.matchAll(/^#{2,3}\s+(KC-P\d+-[A-Z]\d+)\s*$/gm)];return headings.map((match,index)=>{const block=markdown.slice(match.index+(match[0].length),headings[index+1]?.index||markdown.length);const claim={id:match[1]};fields.forEach((field,position)=>{const start=block.search(new RegExp(`^- \\*\\*${field}:\\*\\*`,`m`));if(start<0)return;const tail=block.slice(start).replace(new RegExp(`^- \\*\\*${field}:\\*\\*\\s*`),"");const next=fields.slice(position+1).map(name=>tail.search(new RegExp(`^- \\*\\*${name}:\\*\\*`,`m`))).filter(value=>value>=0);claim[field]=clean(tail.slice(0,next.length?Math.min(...next):tail.search(/^#{2,3}\s/m)>=0?tail.search(/^#{2,3}\s/m):tail.length));});return claim})}
function title(markdown,fallback){return clean((markdown.match(/^#\s+(.+)$/m)||[])[1]||fallback)}
async function load(){const results=await Promise.all(names.map(async(name,index)=>{const path=`${base}${prefix}${name}.md`;const response=await fetch(path);if(!response.ok)throw new Error(`Unable to load Phase ${index+1}`);const markdown=await response.text();return{id:index+1,path,title:title(markdown,`Phase ${index+1}`),claims:parseClaims(markdown)}}));state.phases=results;renderPhases();document.getElementById("readerStatus").textContent=`${results.length} fixed phases loaded · ${results.reduce((sum,phase)=>sum+phase.claims.length,0)} claims available`;selectPhase(2)}
function renderRoute(){const requested=location.hash.slice(1);state.route=["orientation","workspace","reflection"].includes(requested)?requested:"orientation";document.querySelectorAll("[data-panel]").forEach(panel=>panel.hidden=panel.dataset.panel!==state.route);document.querySelectorAll("[data-route]").forEach(link=>link.dataset.route===state.route?link.setAttribute("aria-current","page"):link.removeAttribute("aria-current"));document.getElementById("historicalReader").dataset.readerState=state.route==="orientation"?"unoriented":"oriented"}
function renderPhases(){const nav=document.getElementById("phaseNavigation");nav.replaceChildren(...state.phases.map(phase=>{const button=document.createElement("button");button.type="button";button.textContent=`Phase ${phase.id}`;button.title=phase.title;button.addEventListener("click",()=>selectPhase(phase.id));return button}))}
function selectPhase(id){const phase=state.phases.find(item=>item.id===id);if(!phase)return;state.selectedPhase=phase;state.selectedClaim=null;state.visitedPhases.add(id);document.getElementById("currentSituationTitle").textContent=phase.title.replace(/^M9 Knight Capital Published Historical Walkthrough 01 — /,"");document.getElementById("currentSituationText").textContent=`Read-only fixed artifact · ${phase.claims.length} ledger claims`;document.querySelectorAll("#phaseNavigation button").forEach((button,index)=>index+1===id?button.setAttribute("aria-current","step"):button.removeAttribute("aria-current"));renderClaims();renderEvidence();renderTraceability()}
function renderClaims(){const list=document.getElementById("claimList");if(!state.selectedPhase?.claims.length){list.innerHTML="<p>This phase contains no historical ledger claims.</p>";return}const ul=document.createElement("ul");ul.className="claim-list";state.selectedPhase.claims.forEach(claim=>{const li=document.createElement("li"),button=document.createElement("button");button.type="button";button.className="claim-button";button.textContent=`${claim.id} · ${claim["Claim class"]||"Fixed claim"}`;button.setAttribute("aria-pressed",String(state.selectedClaim?.id===claim.id));button.addEventListener("click",()=>selectClaim(claim));li.append(button);ul.append(li)});list.replaceChildren(ul)}
function selectClaim(claim){state.selectedClaim=claim;state.traceability={claimId:claim.id,sourceId:claim["Source identity"]||null,locator:claim["Citation locator"]||null};renderClaims();renderEvidence();renderTraceability()}
function metadata(claim,keys){const dl=document.createElement("dl");dl.className="metadata";keys.forEach(key=>{if(!claim[key])return;const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=key;dd.textContent=claim[key];dl.append(dt,dd)});return dl}
function renderEvidence(){const target=document.getElementById("evidenceDetail"),claim=state.selectedClaim;if(!claim){target.innerHTML="<p>No claim selected.</p>";return}const text=document.createElement("p");text.className="claim-text";text.textContent=claim["Claim text"]||"Claim text unavailable in fixed block.";const link=document.createElement("a");link.className="source-link";link.href=state.selectedPhase.path;link.target="_blank";link.rel="noopener";link.textContent="Open fixed phase artifact";const add=document.createElement("button");add.type="button";add.textContent=state.workingSet.some(item=>item.id===claim.id)?"In Working Set":"Add to Working Set";add.disabled=state.workingSet.some(item=>item.id===claim.id);add.addEventListener("click",()=>{state.workingSet.push(claim);renderWorkingSet();renderEvidence()});target.replaceChildren(text,metadata(claim,["Claim class","Source identity","Citation locator","Attribution","Source date"]),link,document.createElement("br"),add)}
function renderTraceability(){const target=document.getElementById("traceabilityDetail"),claim=state.selectedClaim;if(!claim){target.innerHTML="<p>No claim-to-source path selected.</p>";return}target.replaceChildren(metadata(claim,["Historical-knowledge status","Hindsight status","Confidence boundary","Contradictory source","Evidence-gap reference","Replay eligibility","Reviewer note"]))}
function renderWorkingSet(){const target=document.getElementById("workingSetList");if(!state.workingSet.length)target.innerHTML="<p>Empty. Membership remains distinct from Evidence.</p>";else{const ul=document.createElement("ul");ul.className="working-set-list";state.workingSet.forEach(claim=>{const li=document.createElement("li"),button=document.createElement("button");li.append(`${claim.id} `);button.type="button";button.className="working-set-remove";button.textContent="Remove";button.addEventListener("click",()=>{state.workingSet=state.workingSet.filter(item=>item.id!==claim.id);renderWorkingSet();renderEvidence()});li.append(button);ul.append(li)});target.replaceChildren(ul)}document.getElementById("workingSetCount").textContent=`${state.workingSet.length} items`}
async function init(){renderRoute();renderWorkingSet();addEventListener("hashchange",renderRoute);window.HistoricalReaderState=state;try{await load()}catch(error){document.getElementById("readerStatus").textContent=`Fixed content unavailable: ${error.message}`}}
return{init,state}})();HistoricalReader.init();
