(function () {
  "use strict";
  const $ = selector => document.querySelector(selector); let focusedId = null;
  const escapeHtml = value => String(value || "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
  const params = () => new URLSearchParams(location.search);
  function contextFromUrl() { const p=params(), id=p.get("context")||p.get("source"); return id ? [{type:p.get("type")||(p.get("source")?"person":"organization"),id,label:p.get("contextLabel")||p.get("label")||"Організаційний контекст"}] : []; }
  function typeLabel(item) { const signature=`${item.mimeType||""} ${item.fileName||""}`.toLowerCase(); if(item.kind==="link")return"Посилання"; if(signature.includes("pdf"))return"PDF"; if(item.mimeType?.startsWith("image/"))return"Зображення"; if(item.mimeType?.startsWith("audio/"))return"Аудіо"; if(item.mimeType?.startsWith("video/"))return"Відео"; if(/csv|tsv|spreadsheet|excel|xlsx/.test(signature))return"Таблиця"; return item.fileName?"Файл":"Текст"; }
  function contextUrl(context) { if(!context)return"index.html"; if(context.type==="person")return`index.html?person=${encodeURIComponent(context.id)}`; return `index.html?context=${encodeURIComponent(context.id)}`; }
  function render() { const query=$("#materialSearch").value.trim().toLocaleLowerCase("uk-UA"); const items=MaterialStore.list().filter(item=>!query||`${item.title} ${item.description} ${MaterialStore.safeSourceName(item)} ${(item.contexts||[]).map(x=>x.label).join(" ")}`.toLocaleLowerCase("uk-UA").includes(query)); $("#materialList").innerHTML=items.length?items.map(item=>`<button class="op-card" data-preview="${escapeHtml(item.id)}"><span>${typeLabel(item)}</span><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description||item.fileName||item.url||"")}</p><small>${MaterialStore.safeSourceName(item)?`Надав(ла): ${escapeHtml(MaterialStore.safeSourceName(item))} · `:""}${new Date(item.contributedAt).toLocaleString("uk-UA")}</small><small>${(item.contexts||[]).map(x=>escapeHtml(x.label)).join(" · ")||"Без прив’язки"}</small></button>`).join(""):`<div class="op-empty"><strong>Матеріалів ще немає</strong><p>Додайте файл, текст, посилання або запис розмови.</p></div>`; }
  function parseDelimited(text, delimiter) { const rows=[]; let row=[],cell="",quoted=false; for(let i=0;i<text.length;i++){const char=text[i],next=text[i+1]; if(char==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(char==='"')quoted=!quoted;else if(char===delimiter&&!quoted){row.push(cell);cell="";}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(cell);if(row.some(value=>value!==""))rows.push(row);row=[];cell="";}else cell+=char;} row.push(cell);if(row.some(value=>value!==""))rows.push(row);return rows.slice(0,500); }
  function tablePreview(text, fileName) { const delimiter=/\.tsv$/i.test(fileName||"")?"\t":((text.match(/\t/g)||[]).length>(text.match(/,/g)||[]).length?"\t":","); const rows=parseDelimited(text,delimiter); if(!rows.length)return`<p class="op-notice">Таблиця порожня.</p>`; const width=Math.max(...rows.map(row=>row.length)); const header=rows[0], body=rows.slice(1); return `<div class="sheet-preview-caption"><strong>Таблиця · ${body.length} рядків · ${width} стовпців</strong><small>Показано до 500 рядків</small></div><div class="sheet-preview" tabindex="0"><table><thead><tr>${Array.from({length:width},(_,i)=>`<th scope="col">${escapeHtml(header[i]||`Стовпець ${i+1}`)}</th>`).join("")}</tr></thead><tbody>${body.map(row=>`<tr>${Array.from({length:width},(_,i)=>`<td>${escapeHtml(row[i]||"")}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`; }
  async function preview(id) { const item=MaterialStore.get(id);if(!item)return;focusedId=id;$("#previewTitle").textContent=item.title;const blob=await MaterialStore.getPayload(id);let body=`<p>${escapeHtml(item.description||item.text||"")}</p>`;if(blob){const url=URL.createObjectURL(blob),signature=`${item.mimeType||""} ${item.fileName||""}`.toLowerCase();if(item.mimeType?.startsWith("image/"))body+=`<img src="${url}" alt="${escapeHtml(item.title)}">`;else if(item.mimeType?.startsWith("audio/"))body+=`<audio controls src="${url}"></audio>`;else if(item.mimeType?.startsWith("video/"))body+=`<video controls src="${url}"></video>`;else if(item.mimeType==="application/pdf")body+=`<object data="${url}" type="application/pdf"><a href="${url}" download>Завантажити PDF</a></object>`;else if(/csv|tsv/.test(signature))body+=tablePreview(await blob.text(),item.fileName);else if(/xlsx|spreadsheetml/.test(signature))body+=`<p class="op-notice"><strong>Попередній перегляд цього Excel-файлу недоступний безпечним локальним способом.</strong><br>Файл збережено без змін; завантажте його для перегляду в табличному редакторі.</p><a href="${url}" download="${escapeHtml(item.fileName)}">Завантажити файл</a>`;else if(item.mimeType?.startsWith("text/"))body+=`<pre>${escapeHtml((await blob.text()).slice(0,30000))}</pre>`;else body+=`<p class="op-notice">Для цього формату доступне збереження і завантаження, але не вбудований перегляд.</p><a href="${url}" download="${escapeHtml(item.fileName)}">Завантажити файл</a>`;}if(item.url)body+=`<p><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">Відкрити посилання</a></p>`;const safeName=MaterialStore.safeSourceName(item),contexts=item.contexts||[];body+=`<dl class="material-meta"><div><dt>Тип</dt><dd>${typeLabel(item)}</dd></div><div><dt>Джерело</dt><dd>${escapeHtml(safeName||"Не вказано")}</dd></div><div><dt>Дата</dt><dd>${new Date(item.contributedAt).toLocaleString("uk-UA")}</dd></div><div><dt>Контекст</dt><dd>${escapeHtml(contexts.map(x=>x.label).join(" · ")||"Без прив’язки")}</dd></div></dl><nav class="material-actions">${contexts.map(context=>`<a href="${contextUrl(context)}">Повернутися до ${escapeHtml(context.label)}</a>`).join("")}<a href="watson.html?${new URLSearchParams({context:id,type:"material",contextLabel:item.title,return:`materials.html?open=${id}`})}">Обговорити з Watson</a></nav>`;if(item.corrections?.length)body+=`<h3>Уточнення</h3>${item.corrections.map(x=>`<p>${escapeHtml(x.text)} · ${new Date(x.at).toLocaleString("uk-UA")}</p>`).join("")}`;$("#previewContent").innerHTML=body;$("#previewDialog").showModal(); }
  $("#addMaterial").onclick=()=>{const p=params();if(p.get("contextLabel")||p.get("label"))$("#sourceName").value=p.get("type")==="person"?(p.get("contextLabel")||p.get("label")):"";$("#materialDialog").showModal();};
  document.addEventListener("click",event=>{const close=event.target.closest("[data-close]");if(close)close.closest("dialog").close();const card=event.target.closest("[data-preview]");if(card)preview(card.dataset.preview);});$("#materialSearch").oninput=render;
  $("#materialCreateForm").onsubmit=async event=>{event.preventDefault();const file=$("#materialFile").files[0];if(!file&&!$("#materialText").value.trim()&&!$("#materialUrl").value){$("#materialText").setCustomValidity("Додайте файл, текст або посилання.");$("#materialText").reportValidity();return;}$("#materialText").setCustomValidity("");await MaterialStore.create({title:$("#materialName").value,description:$("#materialText").value,file,url:$("#materialUrl").value,text:$("#materialText").value,sourcePersonId:params().get("type")==="person"?params().get("context")||params().get("source"):params().get("source"),sourceName:$("#sourceName").value,sourceRole:$("#sourceRole").value,sourceDepartment:$("#sourceDepartment").value,contributedAt:$("#sourceDate").value?new Date($("#sourceDate").value).toISOString():new Date().toISOString(),contexts:contextFromUrl()});event.target.reset();$("#materialDialog").close();render();};
  $("#correctionForm").onsubmit=event=>{event.preventDefault();MaterialStore.correct(focusedId,$("#correctionText").value);$("#correctionText").value="";preview(focusedId);};render();const requested=params().get("open");if(requested)preview(requested);
})();
