(function () {
  "use strict";
  const $ = selector => document.querySelector(selector);
  const escapeHtml = value => String(value || "").replace(/[&<>'"]/g, char => ({ "&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;" })[char]);
  let focusedId = null;
  function params() { return new URLSearchParams(location.search); }
  function contextFromUrl() { const p = params(); return p.get("context") ? [{ type: p.get("type") || "organization", id: p.get("context"), label: p.get("label") || "Організаційний контекст" }] : p.get("source") ? [{ type: "person", id: p.get("source"), label: p.get("label") || "Людина" }] : []; }
  function typeLabel(item) { if (item.kind === "link") return "Посилання"; if (item.mimeType === "application/pdf") return "PDF"; if (item.mimeType?.startsWith("image/")) return "Зображення"; if (item.mimeType?.startsWith("audio/")) return "Аудіо"; if (item.mimeType?.startsWith("video/")) return "Відео"; if (/csv|spreadsheet|excel/.test(item.mimeType || item.fileName || "")) return "Таблиця"; return item.fileName ? "Файл" : "Текст"; }
  function render() { const query = $("#materialSearch").value.trim().toLocaleLowerCase("uk-UA"); const items = MaterialStore.list().filter(item => !query || `${item.title} ${item.description} ${item.sourceName} ${item.contexts.map(x=>x.label).join(" ")}`.toLocaleLowerCase("uk-UA").includes(query)); $("#materialList").innerHTML = items.length ? items.map(item => `<button class="op-card" data-preview="${item.id}"><span>${typeLabel(item)}</span><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description || item.fileName || item.url || "")}</p><small>${item.sourceName ? `Надав(ла): ${escapeHtml(item.sourceName)} · ` : ""}${new Date(item.contributedAt).toLocaleString("uk-UA")}</small><small>${item.contexts.map(x => escapeHtml(x.label)).join(" · ") || "Без прив’язки"}</small></button>`).join("") : `<div class="op-empty"><strong>Матеріалів ще немає</strong><p>Додайте файл, текст, посилання або запис розмови.</p></div>`; }
  async function preview(id) { const item = MaterialStore.get(id); if (!item) return; focusedId = id; $("#previewTitle").textContent = item.title; const blob = await MaterialStore.getPayload(id); let body = `<p>${escapeHtml(item.description || item.text || "")}</p>`; if (blob) { const url = URL.createObjectURL(blob); if (item.mimeType.startsWith("image/")) body += `<img src="${url}" alt="${escapeHtml(item.title)}">`; else if (item.mimeType.startsWith("audio/")) body += `<audio controls src="${url}"></audio>`; else if (item.mimeType.startsWith("video/")) body += `<video controls src="${url}"></video>`; else if (item.mimeType === "application/pdf") body += `<object data="${url}" type="application/pdf"></object>`; else if (item.mimeType.startsWith("text/") || /\.(csv|tsv)$/i.test(item.fileName || "")) { const text = await blob.text(); body += `<pre>${escapeHtml(text.slice(0,30000))}</pre>`; } else body += `<a href="${url}" download="${escapeHtml(item.fileName)}">Завантажити файл</a>`; } if (item.url) body += `<a href="${escapeHtml(item.url)}" target="_blank" rel="noopener">Відкрити посилання</a>`; if (item.sourceName) body += `<dl><dt>Хто надав</dt><dd>${escapeHtml(item.sourceName)}</dd><dt>Контекст</dt><dd>${escapeHtml([item.sourceRole,item.sourceDepartment].filter(Boolean).join(" · "))}</dd></dl>`; if (item.corrections.length) body += `<h3>Уточнення</h3>${item.corrections.map(x=>`<p>${escapeHtml(x.text)} · ${new Date(x.at).toLocaleString("uk-UA")}</p>`).join("")}`; $("#previewContent").innerHTML = body; $("#previewDialog").showModal(); }
  $("#addMaterial").onclick = () => { if (params().get("label")) $("#sourceName").value = params().get("label"); $("#materialDialog").showModal(); }; document.addEventListener("click", e => { const close=e.target.closest("[data-close]"); if(close) close.closest("dialog").close(); const card=e.target.closest("[data-preview]"); if(card) preview(card.dataset.preview); }); $("#materialSearch").oninput=render;
  $("#materialCreateForm").onsubmit=async e=>{e.preventDefault(); const file=$("#materialFile").files[0]; if(!file&&!$("#materialText").value.trim()&&!$("#materialUrl").value){$("#materialText").setCustomValidity("Додайте файл, текст або посилання.");$("#materialText").reportValidity();return;} await MaterialStore.create({title:$("#materialName").value,description:$("#materialText").value,file,url:$("#materialUrl").value,text:$("#materialText").value,sourcePersonId:params().get("source"),sourceName:$("#sourceName").value,sourceRole:$("#sourceRole").value,sourceDepartment:$("#sourceDepartment").value,contributedAt:$("#sourceDate").value?new Date($("#sourceDate").value).toISOString():new Date().toISOString(),contexts:contextFromUrl()}); e.target.reset();$("#materialDialog").close();render();};
  $("#correctionForm").onsubmit=e=>{e.preventDefault();MaterialStore.correct(focusedId,$("#correctionText").value);$("#correctionText").value="";preview(focusedId);}; render();
})();
