(function () {
  "use strict";
  const $=selector=>document.querySelector(selector), escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
  let repository=null;try{repository=new ManagementOSOperatingModel.OperatingModelRepository(new ManagementOSOperatingModel.BrowserPersistenceAdapter());}catch(_){}
  function read(key,property){try{return JSON.parse(localStorage.getItem(key))?.[property]||[];}catch(_){return[];}}
  function entries(){const investigations=read("management-os-user-investigations-v1","investigations").filter(item=>item.status==="closed"&&item.data?.lifecycle?.memory).map(item=>({...item,mode:"investigation"}));const improvements=read("management-os-improvements-v1","items").filter(item=>item.status==="closed"&&item.memory).map(item=>({id:item.id,title:item.idea,closedAt:item.closedAt,conclusion:item.memory.opportunity,mode:"improvement",context:item.context,contextRef:item.contextRef,data:{situation:{summary:item.currentState},organizationContext:item.contextRef||(item.context?{label:item.context}:null),evidence:item.materialIds||[],lifecycle:{decision:item.decision,plan:{description:item.intendedState,...item.plan},steps:item.steps,observations:item.observations,stabilization:item.stabilization,memory:item.memory}}}));return[...investigations,...improvements].sort((a,b)=>String(b.closedAt).localeCompare(String(a.closedAt)));}
  function safePersonLabel(id,label){if(!id||!repository)return label;try{return repository.visiblePersons({purpose:"person-workbench"}).some(person=>person.id===id)?label:"Захищений контекст";}catch(_){return"Захищений контекст";}}
  function safeOwner(owner){if(!owner||!repository)return owner;try{const person=(repository.snapshot()?.persons||[]).find(item=>item.displayName===owner);return person&&!repository.visiblePersons({purpose:"person-workbench"}).some(item=>item.id===person.id)?"Захищений відповідальний":owner;}catch(_){return owner;}}
  function labels(item){const context=item.data?.organizationContext;return[safePersonLabel(context?.type==="person"?(context.elementId||context.id):null,context?.label),safeOwner(item.data?.lifecycle?.decision?.owner)].filter(Boolean);}
  function organizationLink(context){if(!context)return"index.html";if(context.type==="person")return`index.html?person=${encodeURIComponent(context.elementId||context.id||"")}`;return`index.html?context=${encodeURIComponent(context.elementId||context.id||"")}`;}
  function materialIds(item){const raw=item.data?.evidence||[];return[...new Set(raw.map(entry=>typeof entry==="string"?entry:entry.materialId).filter(Boolean))];}
  function render(){const query=$("#memorySearch").value.trim().toLocaleLowerCase("uk-UA"),all=entries(),visible=all.filter(item=>!query||`${item.title} ${item.data.situation.summary} ${item.conclusion} ${labels(item).join(" ")}`.toLocaleLowerCase("uk-UA").includes(query));$("#memoryList").innerHTML=visible.length?visible.map(item=>`<button class="op-card" data-memory="${escapeHtml(item.id)}"><span>${item.mode==="improvement"?"Вдосконалення":"Розслідування"} · ${new Date(item.closedAt).toLocaleDateString("uk-UA")}</span><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.conclusion)}</p><small>${escapeHtml(labels(item).join(" · ")||"Без організаційної прив’язки")}</small></button>`).join(""):`<div class="op-empty"><strong>Завершеної роботи ще немає</strong><p>Пам’ять з’являється лише після людського рішення про стабілізацію і закриття.</p></div>`;const counts={};all.forEach(item=>labels(item).forEach(label=>counts[label]=(counts[label]||0)+1));$("#patternList").innerHTML=Object.entries(counts).filter(([,count])=>count>1).map(([label,count])=>`<p><strong>${escapeHtml(label)}</strong> згадується у ${count} завершених ситуаціях. Це повторення контексту, не доказ спільної причини.</p>`).join("");}
  function open(id){const item=entries().find(entry=>entry.id===id);if(!item)return;const lifecycle=item.data.lifecycle,isImprovement=item.mode==="improvement",context=item.data.organizationContext,materials=materialIds(item).map(id=>MaterialStore?.get(id)).filter(Boolean);$("#memoryTitle").textContent=item.title;$("#memoryDetail").innerHTML=`<p class="memory-boundary">Це завершений запис. Він не змінює поточну організацію і не відкриває закриту роботу для редагування.</p><section><h3>${isImprovement?"Можливість":"Ситуація"}</h3><p>${escapeHtml(item.data.situation.summary)}</p></section>${isImprovement?`<section><h3>Бажаний стан</h3><p>${escapeHtml(lifecycle.plan?.description)}</p></section>`:`<section><h3>Людський висновок про причину</h3><p>${escapeHtml(item.conclusion)}</p></section>`}<section><h3>Рішення</h3><p>${escapeHtml(lifecycle.decision?.text||lifecycle.memory?.decision||"Не збережено")}</p>${lifecycle.decision?.owner?`<small>Відповідальний: ${escapeHtml(lifecycle.decision.owner)}</small>`:""}</section><section><h3>Зміна</h3><p>${escapeHtml(lifecycle.plan?.description||"Опис зміни не збережено")}</p><ol>${(lifecycle.steps||[]).map(step=>`<li>${escapeHtml(step.text)}</li>`).join("")}</ol></section><section><h3>Що спостерігали</h3>${(lifecycle.observations||[]).map(observation=>`<p>${escapeHtml(observation.actual)}${observation.deviation?` · Відхилення: ${escapeHtml(observation.deviation)}`:""}</p>`).join("")||"<p>Спостережень не збережено.</p>"}</section><section><h3>Чому закрили</h3><p>${escapeHtml(lifecycle.stabilization?.basis||lifecycle.memory?.stabilization||"Підставу не збережено")}</p></section>${materials.length?`<section><h3>Пов’язані матеріали</h3><ul>${materials.map(material=>`<li><a href="materials.html?open=${encodeURIComponent(material.id)}">${escapeHtml(material.title)}</a>${MaterialStore.safeSourceName(material)?` · ${escapeHtml(MaterialStore.safeSourceName(material))}`:""}</li>`).join("")}</ul></section>`:""}<nav class="memory-links"><a href="${organizationLink(context)}">Повернутися до ${escapeHtml(context?.label||"організації")}</a>${context?.elementId||context?.id?`<a href="materials.html?context=${encodeURIComponent(context.elementId||context.id)}&type=${encodeURIComponent(context.type||"organization")}&contextLabel=${encodeURIComponent(context.label||"Організація")}">Матеріали цього контексту</a>`:""}<a href="watson.html?${new URLSearchParams({context:item.id,type:"memory",contextLabel:item.title,return:`memory.html?open=${item.id}`})}">Обговорити цей запис з Watson</a></nav>`;$("#saveKnowledge").onclick=()=>sessionStorage.setItem("management-os-knowledge-draft-v1",JSON.stringify({title:item.title,content:`${item.conclusion||item.data.situation.summary}\n\n${lifecycle.stabilization?.basis||""}`,source:`Операційна пам’ять · ${item.id}`}));$("#memoryDialog").showModal();}
  function protectHiddenNames(){if(!repository)return;try{const visible=new Set(repository.visiblePersons({purpose:"person-workbench"}).map(person=>person.id));(repository.snapshot()?.persons||[]).filter(person=>!visible.has(person.id)).forEach(person=>{const walker=document.createTreeWalker($("#memoryDialog"),NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{node.nodeValue=node.nodeValue.split(person.displayName).join("Захищене ім’я");});});}catch(_){}}
  document.addEventListener("click",event=>{const entry=event.target.closest("[data-memory]");if(entry){open(entry.dataset.memory);protectHiddenNames();}if(event.target.closest("[data-close]"))event.target.closest("dialog").close();});$("#memorySearch").addEventListener("input",render);render();const requested=new URLSearchParams(location.search).get("open");if(requested){open(requested);protectHiddenNames();}
})();
