(function(){
  "use strict";
  const $=selector=>document.querySelector(selector),escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);let repository=null,pending=null;
  try{repository=new ManagementOSOperatingModel.OperatingModelRepository(new ManagementOSOperatingModel.BrowserPersistenceAdapter());}catch(_){}
  const route=new URLSearchParams(location.search),context={id:route.get("context")||"",type:route.get("type")||"organization",label:route.get("contextLabel")||"Management OS",returnUrl:route.get("return")||"index.html"};
  const state=()=>repository?.snapshot()||null,stored=(key,property)=>{try{return JSON.parse(localStorage.getItem(key))?.[property]||[];}catch(_){return[];}};
  function add(role,text){$("#conversation").insertAdjacentHTML("beforeend",`<article><strong>${escapeHtml(role)}</strong><p>${escapeHtml(text)}</p></article>`);}
  function retrieve(query){const model=state(),needle=query.toLocaleLowerCase("uk-UA"),words=needle.split(/\s+/).filter(word=>word.length>3),hits=[];(model?.elements||[]).forEach(item=>{if(words.some(word=>`${item.label} ${item.kind}`.toLocaleLowerCase("uk-UA").includes(word)))hits.push(`${item.label} — ${item.kind}`);});(repository?.visiblePersons({purpose:"person-workbench"})||[]).forEach(person=>{if(needle.includes("хто")||words.some(word=>person.displayName.toLocaleLowerCase("uk-UA").includes(word))){const links=(model?.peopleRelationships||[]).filter(link=>link.personId===person.id&&link.lifecycle==="active").map(link=>model.elements.find(item=>item.id===link.targetId)?.label).filter(Boolean);hits.push(`${person.displayName}: ${links.join(" · ")||"контекст не визначено"}`);}});MaterialStore.list().forEach(item=>{const source=MaterialStore.safeSourceName(item);if(words.some(word=>`${item.title} ${item.description} ${source}`.toLocaleLowerCase("uk-UA").includes(word)))hits.push(`Матеріал «${item.title}»${source?`, джерело: ${source}`:""}`);});stored("management-os-user-investigations-v1","investigations").forEach(item=>{if(words.some(word=>`${item.title} ${item.conclusion} ${item.data?.situation?.summary}`.toLocaleLowerCase("uk-UA").includes(word)))hits.push(`${item.status==="closed"?"Завершена":"Активна"} ситуація «${item.title}»: ${item.conclusion||item.data?.situation?.summary}`);});stored("management-os-improvements-v1","items").forEach(item=>{if(words.some(word=>`${item.idea} ${item.context} ${item.currentState}`.toLocaleLowerCase("uk-UA").includes(word)))hits.push(`${item.status==="closed"?"Завершене":"Активне"} вдосконалення «${item.idea}»`);});return hits.slice(0,10);}
  function contextRecord(){if(["investigation","memory"].includes(context.type)){const found=stored("management-os-user-investigations-v1","investigations").find(item=>item.id===context.id);if(found)return found;}if(["improvement","memory"].includes(context.type))return stored("management-os-improvements-v1","items").find(item=>item.id===context.id);return null;}
  function assistance(){const record=contextRecord(),findings=[];if(context.type==="investigation"&&record){const data=record.data||{},evidence=data.evidence||[],hypotheses=data.hypotheses||[],timeline=data.timeline||[];if(!evidence.length)findings.push("До ситуації ще не додано матеріалів.");if(evidence.some(item=>!item.source&&!item.materialId))findings.push("Є матеріал без видимого джерела.");if(hypotheses.some(item=>!(item.evidenceIds||item.supportingEvidence||[]).length))findings.push("Є робоча версія без явної опори на матеріал.");if(timeline.length<2)findings.push("Хронологія ще не показує послідовність подій.");if(data.unknowns?.length)findings.push(`Невирішені прогалини: ${data.unknowns.length}.`);if(record.causeFound&&!data.lifecycle?.decision)findings.push("Причину зафіксовано, але рішення ще не записано.");}if(context.type==="improvement"&&record){if(!record.decision?.owner)findings.push("Для рішення не вказано відповідального.");if(!record.plan?.checkpoint)findings.push("У плані немає контрольної точки.");if(!record.plan?.signal)findings.push("Не визначено очікуваний сигнал зміни.");if(!(record.steps||[]).length)findings.push("Кроки виконання ще не визначено.");if((record.steps||[]).length&&!(record.observations||[]).length)findings.push("Зміна має кроки, але ще не має спостереження.");}return findings;}
  function parseProposal(text){const department=text.match(/(?:підрозділ|відділ|department)\s+[«"]?([^,.;\n»"]+)/i),person=text.match(/(?:людина|керівник|person)\s+[«"]?([^,.;\n»"]+)/i);if(!department&&!person)return null;return{department:department?.[1].trim()||null,person:person?.[1].trim()||null};}
  function showProposal(proposal){pending=proposal;$("#proposal").classList.remove("hidden");$("#proposal").innerHTML=`<article><h2>Пропозиція до моделі організації</h2><p>${proposal.department?`Додати підрозділ «${escapeHtml(proposal.department)}».`:""} ${proposal.person?`Додати людину «${escapeHtml(proposal.person)}» після визначення ролі.`:""}</p><p class="memory-boundary">Watson ще нічого не змінив. Перевірте пропозицію.</p><button type="button" data-confirm>Підтвердити зміну</button><button type="button" data-cancel>Відхилити</button></article>`;}
  function applyProposal(){if(!pending||!repository||!state()){add("Watson","Немає активної організації. Спершу створіть її.");return;}try{repository.transact("watson-confirmed-organization-proposal",model=>{if(pending.department&&!model.elements.some(item=>item.kind==="department"&&item.label===pending.department)){const item=repository.makeElement(model,"department",pending.department,"known");model.elements.push(item);const root=model.elements.find(entry=>entry.kind==="organization");if(root)repository.addRelationshipToState(model,{family:"containment",fromId:root.id,toId:item.id,label:"містить"});}return{applied:true};});add("Watson",`Підтверджену зміну застосовано одним кроком. Поверніться до «${context.label}», щоб перевірити результат.`);pending=null;$("#proposal").classList.add("hidden");}catch(error){add("Watson",`Зміну не застосовано: ${error.message}. Попередній стан збережено.`);}}
  function providerConfig(){try{return JSON.parse(sessionStorage.getItem("management-os-watson-provider-v1"));}catch(_){return null;}}
  async function providerAnswer(question,hits){const config=providerConfig();if(!config)return null;const safeContext=`Контекст: ${context.type} — ${context.label}. Сигнали уваги:\n${assistance().join("\n")||"Немає"}\nЛокальний пошук:\n${hits.join("\n")||"Немає"}`;const response=await fetch(config.endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${config.key}`},body:JSON.stringify({model:config.model,messages:[{role:"system",content:"Ти Watson у Management OS. Відповідай українською. Не вигадуй даних, не встановлюй Причину і не виконуй мутацій."},{role:"user",content:`${safeContext}\n\nПитання: ${question}`}]})});if(!response.ok)throw new Error("AI provider не відповів успішно.");const data=await response.json();return data.choices?.[0]?.message?.content||null;}
  $("#watsonForm").addEventListener("submit",async event=>{event.preventDefault();const text=$("#watsonInput").value.trim();add("Ви",text);$("#watsonInput").value="";const proposal=parseProposal(text);if(proposal){showProposal(proposal);return;}const hits=retrieve(text);try{const answer=await providerAnswer(text,hits);add("Watson",answer||(hits.length?hits.join("\n"):"У доступних даних цього не знайдено. Я не буду вигадувати відповідь."));}catch(error){add("Watson",`${error.message} Локальний пошук продовжує працювати.\n${hits.join("\n")}`);}});
  $("#configureProvider").onclick=()=>$("#providerDialog").showModal();$("#providerForm").onsubmit=event=>{event.preventDefault();sessionStorage.setItem("management-os-watson-provider-v1",JSON.stringify({endpoint:$("#providerEndpoint").value,model:$("#providerModel").value,key:$("#providerKey").value}));$("#providerDialog").close();$("#watsonStatus").textContent="AI provider налаштовано для цієї вкладки · локальні можливості залишаються доступними";};document.addEventListener("click",event=>{if(event.target.closest("[data-confirm]"))applyProposal();if(event.target.closest("[data-cancel]")){pending=null;$("#proposal").classList.add("hidden");}if(event.target.closest("[data-provider-close]"))$("#providerDialog").close();});
  const findings=assistance();$("#watsonContext").innerHTML=`<strong>Зараз: ${escapeHtml(context.label)}</strong><p>${context.type==="organization"?"Watson бачить дозволену модель організації та локальну операційну пам’ять.":`Контекст: ${escapeHtml(context.type)}. Вам не потрібно повторно пояснювати, де ви працюєте.`}</p>${findings.length?`<h3>Варто перевірити</h3><ul class="assistant-checks">${findings.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul>`:"<p>Явних структурних прогалин у доступному записі не виявлено.</p>"}<a href="${escapeHtml(context.returnUrl)}">Повернутися до ${escapeHtml(context.label)}</a>`;if(providerConfig())$("#watsonStatus").textContent="AI provider налаштовано для цієї вкладки · локальні можливості залишаються доступними";
})();
